### ISSUE TITLE
Package auto discovery not working

### ISSUE THREAD

**Issue by prokawsar** [prokawsar/PasswordValidator-Package#3]

**Comment by Juhlinus** [comment]
![Imgur](https://i.imgur.com/USuSIYo.png)

Works fine for me!

**Comment by j3rrey** [comment]
Just checked the code and installed the package, auto-discovery works fine for me!
![screen shot 2018-10-02 at 16 01 47](https://user-images.githubusercontent.com/5716777/46353464-870f0700-c65c-11e8-8744-d0e95fe65a40.png)
<img width="428" alt="screen shot 2018-10-02 at 15 59 25" src="https://user-images.githubusercontent.com/5716777/46353465-870f0700-c65c-11e8-8b5a-6d0e7c8e889d.png">

**Comment by prokawsar** [comment]
Thanks for testing and time.
